
export const GET_MOVIES = 'GET_MOVIES'
export const GET_MOVIE_DETAIL = 'GET_MOVIES_DETAIL'
export const SET_NULL_MOVIE_DETAIL = 'SET_NULL_MOVIE_DETAIL'
export const ADD_MOVIE_FAVORITES = 'ADD_MOVIE_FAVORITES'